#!/bin/sh

CONTENT=$(cat /usr/src/random-wisdom/wisdom.json)

LENGTH=$(echo $CONTENT | jq '. | length')
CHOICE=$(($RANDOM % $LENGTH))

ATTRIBUTION=$(echo $CONTENT | jq ".[$CHOICE] | .attribution" | tr -d '"')
WISDOM=$(echo $CONTENT | jq ".[$CHOICE] | .wisdom"| tr -d '"')

echo $ATTRIBUTION: $WISDOM

set -x

curl -X PUT -H "Content-Type: text/plain" -d "$ATTRIBUTION" $METADATA_API_URL/outputs/attribution
curl -X PUT -H "Content-Type: text/plain" -d "$WISDOM" $METADATA_API_URL/outputs/wisdom
