#!/bin/sh

CONTENT=$(cat /usr/src/random-wisdom/wisdom.json)

LENGTH=$(echo $CONTENT | jq '. | length')
CHOICE=$(($RANDOM % $LENGTH))

ATTRIBUTION=$(echo $CONTENT | jq ".[$CHOICE] | .attribution")
WISDOM=$(echo $CONTENT | jq ".[$CHOICE] | .wisdom")

echo $ATTRIBUTION: $WISDOM

echo $METADATA_API_URL

echo "curl -X POST -H \"Content-Type: text/plain\" -d $ATTRIBUTION $METADATA_API_URL/outputs/attribution"
echo "curl -X POST -H \"Content-Type: text/plain\" -d $WISDOM $METADATA_API_URL/outputs/wisdom"

curl -X POST -H "Content-Type: text/plain" -d $ATTRIBUTION $METADATA_API_URL/outputs/attribution
curl -X POST -H "Content-Type: text/plain" -d $WISDOM $METADATA_API_URL/outputs/wisdom
